### PR TITLE
Adopt rspec to use with chef

### PR DESCRIPTION
**Pull request by cosmonaut-ok**

### CODE REVIEW

**Comment by dgutov** [comment]
Nice. Does it work without any further changes?

**Comment by pezra** [comment]
👍

**Comment by cosmonaut-ok** [comment]
Chefspec uses to perform chef recipes testing. Chefspec built on top of rspec (written on rspec DSL), so, there is no differences, how to run rspec for chef and non-chef code. But, it should be launched from chef cookbook root directory, which could not contain Rakefile or Gemfile. As usual Berkshelf uses to manage chef dependencies, so Berksfile should be present in cookbook root directory.

**Comment by dgutov** [comment]
Thanks for the explanation!

**Comment by mcg** [comment]
This doesn't appear to work correctly with the default location ChefSpec stores specs. A cookbook with a path like `recipes/default.rb` will look for it's spec in `spec/recipes/default_spec.rb`. However, ChefSpec stores it's specs in `spec/unit/recipes`. So the correct location for this spec would be `spec/unit/recipes/default_spec.rb`.  Have I missed support for this being able to include an arbitrary directory in the spec path, such as `unit` in this case?

**Pull request merged**
