### PR TITLE
Add `rspec-autosave-buffer` variable

### PR DESCRIPTION
**Pull request by asok**
It is safe to assume that if `rspec-verify` and `rspec-verify-single`
are called from a dirty buffer that the user will want it to be saved first.

### CODE REVIEW

**Comment by dgutov** [comment]
This seems inadequate:

* What if the edited buffer is the other one (the code, or the test) than we're currently in?

* What about the other commands, like `-matching` and `-continue`?

Either way, I think this should be disabled by default: `save-some-buffers`, called by `compile`, functions just fine, and occasionally it helps me find a character typed by mistake.

**Comment by asok** [comment]
> What if the edited buffer is the other one (the code, or the test) than we're currently in?

The call to `(rspec-spec-or-target)` takes care of that. That is it will only autosave in case the current buffer is the code or the test.
> What about the other commands, like -matching and -continue?

Did not know about those commands. I've forced pushed the fix for it.

**Comment by dgutov** [comment]
> That is it will only autosave in case the current buffer is the code or the test.

But it'll only save the current one, right?

**Comment by asok** [comment]
Yes it `save-buffer` saves the current buffer if modified.

**Comment by dgutov** [comment]
> Did not know about those commands. I've forced pushed the fix for it.

Maybe you should also update the new variable's docstring somehow.

**Comment by asok** [comment]
Ah yes thanks for pointing that out.

**Comment by dgutov** [comment]
All right, thanks for the corrections.

**Pull request merged**
