### PR TITLE
Point out potential need for rspec-use-rvm

### PR DESCRIPTION
**Pull request by davidw**

### CODE REVIEW

**Comment by dgutov** [comment]
The text looks good, but I think it should go further down, into "Gotchas".

**Comment by davidw** [comment]
It's not a 'gotcha', it's part of the installation if you use RVM.  Without it, it won't work.

**Comment by dgutov** [comment]
> Without it, it won't work.

That's not true. First, if you use only one Ruby version, calling `(rvm-use-default)`, like [documented in rvm.el's README](https://github.com/senny/rvm.el#installation), will do the trick.

Second, if you routinely switch between projects that use different versions of Ruby, you're going to have problems with other packages that deal with Ruby as well (such as `inf-ruby`), unless you call `rvm-activate-corresponding-ruby` each time, or add it to `ruby-mode-hook`. That's mentioned in the same README, under Usage.

And if you do that, you won't even need `rspec-use-rvm`.

**Comment by davidw** [comment]
It sounds like between what I wrote, and what you wrote above, you have a pretty good idea of what should go in the README.  Probably makes more sense for you to make those changes.

**Comment by dgutov** [comment]
Yes and no: I've never actually used RVM with Emacs (at least to my recollection).

Would "call `M-x rbm-activate-corresponding-ruby` each time when you switch between projects" satisfy you as an advice?

There's a mistake in my previous message: you can't add it to `ruby-mode-hook`: the "current Ruby" setting is global.

**Comment by marcofognog** [comment]
+1 this commit was helpfull

**Comment by dgutov** [comment]
Too bad this PR puts the section too high.

**Comment by marcofognog** [comment]
#164

**Pull request closed without merging**
