### PR TITLE
Feature/find feature specs for controllers

### PR DESCRIPTION
**Pull request by trodrigu**

### CODE REVIEW

**Comment by trodrigu** [comment]
Good evening, I just wanted to share the addition of feature specs instead of the controller specs as that is what the movement is towards.

**Comment by dgutov** [comment]
Does `rspec-rails` also use this organization?

I thought the thing with differently named test directories was only for test/unit, which Rails defaults to.

**Comment by trodrigu** [comment]
@dgutov The recommendation on `rspec-rails` is if you want to render views and test the whole stack then a [request](https://github.com/rspec/rspec-rails#request-specs) spec is the way to go.  This PR was not ready to go so therefore I closed it until it's ready to go.  Ideally I was thinking that we should give a user a choice like when you `SPC m g g` (spacemacs) for the go to method and it returns multiple instances of such.  Although there may be an easier way to do this.

**Comment by trodrigu** [comment]
Rather I was missing the toggle action from `, T <TAB>`

**Pull request closed without merging**
